### ISSUE TITLE
fix: docker builds don't squash the intermediary layers

### ISSUE THREAD

**Issue by dperson** [blue-build/cli#118]
I try to create as few as possible anyway, but COPYs etc. creep up as the best way to handle things.

The custom layers are now showing:
`custom layers needed: 24 (1.4 GB)`

Compared to the previous builds with buildah:
`custom layers needed: 2 (968 MB)`

I do appreciate that they are a bit faster, but is there any way you can re-enable squashing? Thanks.

**Comment by xynydev** [comment]
What's the benefit of squashing anyway? Layers allow for diffs, right?

**Comment by dperson** [comment]
Well for these uBlue OS builds in particular lots of things get copied into /tmp to be used by the RUN, when they are on different layers the "delete" doesn't do anything except make it look neater.

**Comment by dperson** [comment]
I personally don't view a 33% reduction in build time and a 150% increase in image size as a win... what is the goal of the change? What is it providing or fixing? Thanks.

**Comment by xynydev** [comment]
I'm curious on what causes the built images to become so large. That certainly wasn't a foreseen consequence of switching to docker for builds. It could be the squashing, or it could be something in Docker itself that's different? #112 might be related, maybe buildah uses compression by default and Docker doesn't?

**Comment by gmpinder** [comment]
BlueBuild no longer has custom layers. All layers are run with `ostree container commit` (except user created `containerfile` modules). Any present custom layers should be brought up with upstream image creators.

**Comment by fiftydinar** [comment]
I use v1.3 of GitHub action, which includes v0.8.3 version of BlueBuild CLI at the moment.

I get 400MB of needed custom layers when there is nothing of packages to update & around 1GB when I do some slight updates to RPMs (2 small Gnome extensions with only some minor file changes).

I don't remember this behavior in legacy template, which used buildah.

I don't know if this behavior is due to how docker handles things in CLI or due to how upstream base image is built, but I'm just noting this as another reported behavior.
