### ISSUE TITLE
Endless workflow run if 500 internal server error occurs while uploading a blob.

### ISSUE THREAD

**Issue by sukarn-m** [blue-build/cli#211]
I've seen an endless workflow run both with and without `use_unstable_cli`, but I have the logs from only the run with `use_unstable_cli` enabled. These workflows ran until they were manually cancelled.

The actual error encountered was `Error: writing blob: uploading layer to https://ghcr.io/v2/sukarn-m/sukarn-ublue-budgie/blobs/upload/a249cf7b-fecd-441b-92b7-720ae21d328f?digest=sha256%3A7d976e0748affe381d4b3e77472afd2a2a2a38aa2c5d849e148eb4909155e340: received unexpected HTTP status: 500 Internal Server Error`.

The error occurred during the `Pushing image` stage of the workflow, but it did not stop the workflow.

Attachment: [workflow_logs_26708568167.zip](https://github.com/user-attachments/files/16485302/workflow_logs_26708568167.zip)

**Comment by gmpinder** [comment]
I believe this was due to a panic when underflowing on the retry logic which has been fixed in https://github.com/blue-build/cli/commit/464fdf94a919d94f8b0edebb757177c0195f9f33 and released in `v0.8.12`. Are you still encountering this issue?

**Comment by sukarn-m** [comment]
It only occurred twice at the time I initially reported it on Discord and here. I haven't encountered it since then. I'm closing this issue as I have no reliable way of reproducing the issue.

**Comment by gmpinder** [comment]
Another update, turns out the fix I posted above was just helping to get rid of the possibility of a panic in a part of the code. The main reason it would hang was because we weren't handling the app thread panicking properly. It would panic and just stay running as the main thread is used for catching signals like `SIGINT`, `SIGTERM`, and so on. With the fix here https://github.com/blue-build/cli/commit/7418f60f8e08f229db809c793f6d5fd096057603, we will now ensure the program exits properly if the app thread panics. This has been released in the `v0.8.13` patch.
