### ISSUE TITLE
Nvidia akmods logic needs to be updated

### ISSUE THREAD

**Issue by fiftydinar** [blue-build/cli#240]
Ublue dropped versioning, so it always builds the newest one.
Which means that `nvidia-version` entry is no longer needed.

Maybe `nvidia: false` by default can substitute legacy `nvidia-version` entry.

They also build the image in proprietary & open kernel module, so they are versioned like this:
`ghcr.io/ublue-os/akmods-nvidia:main-${OS_VERSION}`
`ghcr.io/ublue-os/akmods-nvidia-open:main-${OS_VERSION}`

Maybe `nvidia: open/proprietary` entry option looks good.

What do you think?

**Comment by gmpinder** [comment]
I don't know if switching from a boolean to an enum would be a smart move. If I can find a way to accept both a bool and enum, that could work. We would have `nvidia: true` be equivalent to `nvidia: proprietary` since that logic would bear the same image. For `nvidia-version`, we can just ignore it/let the json schema handle validation.
