### ISSUE TITLE
Add way to use tags that replace the auto-generated tags

### ISSUE THREAD

**Issue by noahdotpy** [blue-build/cli#272]
My use case is this: I maintain my personal Fedora image that has three frequencies, which define how often you want a build throughout the week. These frequencies include `weekly` (default), `git`, and `daily`. These frequencies are included in the image tag inputted to `bootc switch`.

All of these frequencies are built by making a separate image recipe file for each frequency. This means there will be multiple image recipes that have the exact same same, but with different `alt-tags` matching the frequency and channel (just if I want `current` or `previous` fedora).

This however, brings a problem that I cannot solve. The `41` tag (fedora version) is common to all images that are on fedora 41. This basically acts like the `daily` tag because basically what it does is it builds the image daily _and_ on git push. If you remember, I want the default to be `weekly` frequency when a frequency is not specified (such as `41` or `current`).

**Proposal 1**

My first proposal is a key in the image recipe called `disable-default-tags` that disables the default tags generated by bluebuild and only uses the tags in the `tags` key (renamed from `alt-tags`).

**Proposal 2**

The second proposal is that there would be an option in the `bluebuild build` command that specifies the tags that are to be used. This would also be an optional option in the github action. The tag generation should be able to be automated in the github action.

**Comment by xynydev** [comment]
Option 2 sounds sensible to me.

**Comment by noahdotpy** [comment]
I think so too. It is a pretty niche feature I feel and usually you would probably have custom tag generation automated to at least some extent.

**Comment by noahdotpy** [comment]
I just realised that this isn't a problem in my case because it was merged a while ago to address these conflicting tags. The proposals still stand.

**Comment by gmpinder** [comment]
Unfortunately, option 2 won't really work with a new feature coming out to build multiple recipes. It'll take in any number of recipe files and build them all at once, so adding an arg won't really help in this case as we wouldn't be able to tell which recipe should get those tags. As for option 1, our next version of the recipe file format will be renaming it to `tags`, but we're still planning on keeping the other tags.

Since your original issue is no longer a problem I'll close this out. Appreciate the feedback though!
