### ISSUE TITLE
Separate out NVIDIA drivers as an akmods

### ISSUE THREAD

**Issue by arashsm79** [blue-build/cli#279]
Thanks for this tool. I have been using it for a couple month now.

One issue I have come across multiple times is that when I update to a new image (the ones with 'nvidia' in their name), I also get the latest NVIDIA driver and Linux kernel. This has caused issues every time I update my system as I keep hitting upstream driver bugs with my system (games crash, suspend gets broken, sometimes there is a specific bug that happens with certain kernel versions and …)

I was wondering if there is a way  (or would be cool to have a feature) to declaratively specify:

- The NVIDIA driver version
- The Linux kernel version

This would be immensely useful as I can keep getting the latest updates to my desktop environment without having to deal with the issues that come with the latest NVIDIA/Linux kernel versions (especially on optimus laptops).

For example, we could have an akmods for NVIDIA drivers with specific versions so that we could install it on top of non '-nvidia' images.

**Comment by xynydev** [comment]
I'm not sure any project provides akmods for arbitrary Nvidia driver versions at this time. This is not something we're really well-equipped to provide either. I'm not sure if the kernel version parameter would be meant to do the same thing, but the same concerns apply there.

Of course feel free to correct me if I'm wrong and there is a viable way to do this technically, I do agree that a feature like this would be cool and useful, I'm just not sure we have the resources to do it.

**Comment by fiftydinar** [comment]
Yeah, since you're using Universal Blue's `nvidia` image, that's more of their concern. However, it would be a huge maintenance job to provide older versions of Nvidia akmods, while assuring that they would build correctly for latest kernel versions. Universal Blue dropped `470` & just focus on latest Nvidia versions, with no plan to change that. RPMFusion & Negativo repos also provide just latest Nvidia driver version, so I guess you will be stuck in this situation.

**Comment by gmpinder** [comment]
Closing as an upstream issue
