### ISSUE TITLE
removing /tmp/ and /var/

### ISSUE THREAD

**Issue by xynydev** [blue-build/cli#64]
Currently only the final step in the generated Containerfile removes /tmp/ and /var/, which I believe lets other layers have the files with a newer layer in the container removing them.

Maybe these should also be added to the end of every module run command? It's starting to look pretty cluttered, though...

**Comment by gmpinder** [comment]
I'm not too worried about clutter since the Containerfile is generated. The only problem I see is that we are binding to `/tmp/config` and `/tmp/modules`. Calling `rm -fr /tmp/*` after each module run would wipe the configs and modules being stored there. What we could do is make use of the [tmpfs](https://docs.docker.com/engine/reference/builder/#run---mounttypetmpfs) mount and mount to `/tmp` and `/var` during those. Then they won't even stick around after a build and we don't have to worry about anything getting layered into the final image.

**Comment by gmpinder** [comment]
> I think we can take advantage of buildx caching and sort our layers a bit better. I have been ready heavily on caching and how layers are reevaluated. Most our package installs should be in the beginning of the file and only copy what we need at the end.
> 
> Whenever a later is reevaluated, it reevaluates each following layer. So if you move a file and the copy command is first. It rebuilds the entire image

Yes, but I'm of the opinion that the user should have the ability to decide which is layered first. I have scripts that have to run in a certain order so I wouldn't want the cli tool to decide which order that would be outside of the order in my recipe.

**Comment by xynydev** [comment]
I agree with @gmpinder. I naturally order my recipe like files -> packages -> the rest (scripts and modules that pull from the web or git coming lsst).
